/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import daos.EmpruntDao;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Emprunt;

/**
 *
 * @author CAESAR
 */
public class GestionAmendesFrame extends javax.swing.JFrame {

    private EmpruntDao empruntDao;
    private static final int DUREE_EMPRUNT_JOURS = 14;
    private static final double TARIF_PAR_JOUR = 1.0;

    /**
     * Creates new form GestionAmendesFrame
     */
    public GestionAmendesFrame() {
        initComponents();
        empruntDao = new EmpruntDao();
        actualiserTable();
    }

    private void actualiserTable() {
        List<Emprunt> emprunts = empruntDao.listerTous();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        Date today = new Date();
        for (Emprunt e : emprunts) {
            int joursRetard = calculerJoursRetard(e, today);
            if (joursRetard > 0) {
                double amende = joursRetard * TARIF_PAR_JOUR;
                model.addRow(new Object[]{
                    e.getId(),
                    e.getIdLivre(),
                    e.getIdAbonne(),
                    e.getDateEmprunt(),
                    joursRetard,
                    amende
                });
            }
        }
    }

    private int calculerJoursRetard(Emprunt emprunt, Date today) {
        if (emprunt == null || emprunt.getDateEmprunt() == null) {
            return 0;
        }
        Date dateReference = today;
        if (emprunt.getDateRetour() != null) {
            dateReference = emprunt.getDateRetour();
        }
        long diffMs = dateReference.getTime() - emprunt.getDateEmprunt().getTime();
        long joursEcoules = diffMs / (1000L * 60L * 60L * 24L);
        long retard = joursEcoules - DUREE_EMPRUNT_JOURS;
        return (int) Math.max(0, retard);
    }

    private void calculerAmende() {
        String idStr = jTextField2.getText().trim();
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir l'ID Emprunt.");
            return;
        }
        try {
            int id = Integer.parseInt(idStr);
            Emprunt e = empruntDao.trouverParId(id);
            if (e == null) {
                JOptionPane.showMessageDialog(this, "Aucun emprunt trouvé avec l'ID " + id);
                return;
            }
            int joursRetard = calculerJoursRetard(e, new Date());
            double amende = joursRetard * TARIF_PAR_JOUR;
            JOptionPane.showMessageDialog(this,
                    "Jours de retard: " + joursRetard + "\nAmende: " + amende + " $");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID Emprunt invalide.");
        }
    }

    private void payerAmende() {
        String idStr = jTextField2.getText().trim();
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir l'ID Emprunt.");
            return;
        }
        try {
            int id = Integer.parseInt(idStr);
            Emprunt e = empruntDao.trouverParId(id);
            if (e == null) {
                JOptionPane.showMessageDialog(this, "Aucun emprunt trouvé avec l'ID " + id);
                return;
            }
            empruntDao.retournerEmprunt(id, new Date());
            JOptionPane.showMessageDialog(this, "Amende payée / emprunt retourné.");
            jTextField2.setText("");
            actualiserTable();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID Emprunt invalide.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnCalculAmende = new javax.swing.JButton();
        btnPayerAmende = new javax.swing.JButton();
        btnActualiserAmende = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Emprunt :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Livre", "ID Abonné", "Date Emprunt", "Jours Retard", "Amaende $"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Gestion Amende");

        btnCalculAmende.setText("Calculer Amende");
        btnCalculAmende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculAmendeActionPerformed(evt);
            }
        });

        btnPayerAmende.setText("Payer Amende");
        btnPayerAmende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayerAmendeActionPerformed(evt);
            }
        });

        btnActualiserAmende.setText("Actualiser");
        btnActualiserAmende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserAmendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculAmende)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPayerAmende)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualiserAmende)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 312, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculAmende)
                            .addComponent(btnPayerAmende)
                            .addComponent(btnActualiserAmende))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnCalculAmendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculAmendeActionPerformed
        calculerAmende();
    }//GEN-LAST:event_btnCalculAmendeActionPerformed

    private void btnPayerAmendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayerAmendeActionPerformed
        payerAmende();
    }//GEN-LAST:event_btnPayerAmendeActionPerformed

    private void btnActualiserAmendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserAmendeActionPerformed
        actualiserTable();
    }//GEN-LAST:event_btnActualiserAmendeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAmendesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAmendesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAmendesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAmendesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAmendesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiserAmende;
    private javax.swing.JButton btnCalculAmende;
    private javax.swing.JButton btnPayerAmende;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
